name: phosphor_flutter
description: Implementation of Phosphoricons for Flutter. 772 icons and counting. Regular, Bold.
version: 2.1.0
maintainer: Rurick Maqueo Poisot @rurickdev
homepage: https://phosphoricons.com/
repository: https://github.com/kalucky0/phosphor_flutter

environment:
  flutter:  ">=3.38.0 <4.0.0"
  sdk: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: PhosphorBold
      fonts:
        - asset: lib/fonts/Phosphor-Bold.ttf
          weight: 400
    - family: PhosphorRegular
      fonts:
        - asset: lib/fonts/Phosphor.ttf
          weight: 400
